apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kffdzo2n9-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/kffdzo2n9-dotnet-basic-gitops